FROM python:3.7
WORKDIR /app
COPY requirements.txt ./requirements.txt 
COPY all_df.csv ./all_df.csv
COPY classifier.pkl ./classifier.pkl
COPY keyword_count_vect.pkl ./keyword_count_vect.pkl
COPY keyword_dict_renew.txt ./keyword_dict_renew.txt
COPY keyword_mat.pkl ./keyword_mat.pkl
COPY tfidf_matrix.pkl ./tfidf_matrix.pkl
RUN pip3 install -r requirements.txt
EXPOSE 8080
COPY . /app
CMD streamlit run --server.port 8080 --server.enableCORS false streamlit.py